DBSettings:
  dbUser: pguser
  dbPassword: pgpwd
  dbHost: 127.0.0.1
  dbPort: 5432
  dbName: testdb

ProgramSettings:
  bindAddress: 127.0.0.1
  port: 8080
  jiraUrl: https://issues.apache.org/jira/rest/api/2/
  threadCount: 1
  issueInOneRequest: 13
  maxTimeSleep: 300ms
  minTimeSleep: 10ms