DBSettings:
  dbUser: pguser
  dbPassword: pgpwd
  dbHost: 127.0.0.1
  dbPort: 5432
  dbName: testdb

ProgramSettings:
  bindAddress: 127.0.0.1
  port: 8080
  jiraUrl: "dsdsd"
  threadCount: 3
  issueInOneRequest: 500
  maxTimeSleep: 300ms
  minTimeSleep: 10ms